# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: teacher.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rteacher.proto\"?\n\x0bTeacherData\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x10\n\x08phone_no\x18\x02 \x02(\t\x12\x10\n\x08password\x18\x03 \x02(\t\"#\n\x10RegisterResponse\x12\x0f\n\x07message\x18\x01 \x02(\t\"j\n\x08Teachers\x12#\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x15.Teachers.TeacherData\x1a\x39\n\x0bTeacherData\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x10\n\x08phone_no\x18\x02 \x02(\t\x12\n\n\x02id\x18\x03 \x02(\x05\"\x15\n\x04Temp\x12\r\n\x05\x66ield\x18\x01 \x01(\t2W\n\x07Teacher\x12-\n\x08Register\x12\x0c.TeacherData\x1a\x11.RegisterResponse\"\x00\x12\x1d\n\x07ShowAll\x12\x05.Temp\x1a\t.Teachers\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'teacher_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TEACHERDATA']._serialized_start=17
  _globals['_TEACHERDATA']._serialized_end=80
  _globals['_REGISTERRESPONSE']._serialized_start=82
  _globals['_REGISTERRESPONSE']._serialized_end=117
  _globals['_TEACHERS']._serialized_start=119
  _globals['_TEACHERS']._serialized_end=225
  _globals['_TEACHERS_TEACHERDATA']._serialized_start=168
  _globals['_TEACHERS_TEACHERDATA']._serialized_end=225
  _globals['_TEMP']._serialized_start=227
  _globals['_TEMP']._serialized_end=248
  _globals['_TEACHER']._serialized_start=250
  _globals['_TEACHER']._serialized_end=337
# @@protoc_insertion_point(module_scope)
